db:
  image: mysql
  ports: 
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: inside
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
  volumes:
    - "./db:/docker-entrypoint-initdb.d"

tomcat:
  image: tomcat:latest
  ports:
    - "8080:8080"
  volumes:
    - "./tomcat/webapps:/usr/local/tomcat/webapps"
  links:
    - db
